sudo: false
language: node_js
node_js:
  - "8"
install:
  - yarn install
script:
  - yarn run build
cache:
  yarn: true
  directories:
    - "node_modules"

# Prevents linting errors from failing build
# May want to change this later
env:
  - CI=false
    
# Take this out when testing is complete
branches:
  only:
    - travis-setup